### ISSUE TITLE
Is the project discontinued ?

### ISSUE THREAD

**Issue by Mohsen7s** [twbs/ratchet#832] opened 2016-06-13 04:30 UTC
I have seen no commits for 3 months and also there is lot's of issues and pull requests that needs to get maintained. Is the project still continuing ?

However this is the best way to create native-like mobile apps.
Hope itcontinue with support

**Comment by Johann-S** [comment] 2016-06-13 07:11
See : https://github.com/twbs/ratchet/issues/792

**Comment by mazong1123** [comment] 2016-07-31 16:31
@Mohsen7s I like this project as you. I don't want it to be dead. So I forked this project: https://github.com/mazong1123/ratchet-pro

Issues and PRs are welcome. I'm using ratchet-pro in my production environment so I'm going to make it more sophisticated but keep lightweight.

**Comment by cvrebert** [comment] 2016-09-28 04:57
Duplicate of #792.

**Closed as completed by cvrebert** 2016-09-28 04:57 UTC
